trigger:
  branches:
    include:
    - main

stages:
- stage: __default
  jobs:
  - job: Job
    pool:
      vmImage: 'windows-latest'   # 建議搭配 windows-latest，可避開 Agent 版本 Demand 錯誤
    steps:
    - task: NodeTool@0
      inputs:
        versionSpec: '20.x'
      displayName: 'Install Node.js'

    - task: CmdLine@2
      displayName: 'npm install and build'
      inputs:
        script: |
          npm install
          npm run build
    - task: WhiteSource@21
      inputs:
        cwd: '$(System.DefaultWorkingDirectory)'